kind: Deployment
apiVersion: apps/v1
metadata:
  name: socketio
  labels:
    app: socketio

spec:
  replicas: 8
  selector:
    matchLabels:
      app: socketio
  template:
    metadata:
      labels:
        app: socketio
    spec:
      containers:
        - name: socketio
          image: socketio
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: socketio
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: session_id
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
spec:
  ports:
    - name: web
      port: 3000
      targetPort: 3000

  selector:
    app: socketio

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: socketio-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: socketio
            port:
              name: web