apiVersion: apps/v1
kind: Deployment
metadata:
  name: socketio
  labels:
    app: socketio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socketio
  template:
    metadata:
      labels:
        app: socketio
    spec:
      containers:
      - name: socketio
        image: socketio
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: socketio
  annotations:
          #traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
          #traefik.ingress.kubernetes.io/service.sticky.cookie.name: session_id
          #traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
spec:
  selector:
    app: socketio
  ports:
  - name: web
    port: 80
    targetPort: 3000
    

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: socketio
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`api.ashish.net`)
    kind: Rule
    #middlewares:
    #- name: sticky-socketio
    services:
    - name: socketio
      port: 80
      #sticky:
      #  cookie:
      #    httpOnly: true
      #    name: cookie


